spring.application.name=numbergame

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
spring.datasource.url=jdbc:postgresql://localhost:5432/numbergame
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-
class-name=org.postgresql.Driver
mybatis.mapper-locations=classpath:/mapper/*.xml